import { loadPack } from "@/lib/pack-store";
import { notFound } from "next/navigation";
import { Flashcard } from "./Flashcard";
import { PracticeCard } from "./PracticeCard";

export const dynamic = "force-dynamic";

function Stat({ value, label, color }: { value: string | number; label: string; color: "accent" | "ok" | "warn" | "cyan" }) {
  const cls = { accent: "text-accent", ok: "text-ok", warn: "text-warn", cyan: "text-cyan" }[color];
  const ring = { accent: "from-accent/20", ok: "from-ok/20", warn: "from-warn/20", cyan: "from-cyan/20" }[color];
  return (
    <div className={`relative rounded-2xl border border-line bg-gradient-to-b ${ring} to-panel overflow-hidden card-glow`}>
      <div className="relative p-5">
        <div className={`text-3xl font-black tracking-tight ${cls}`}>{value}</div>
        <div className="text-xs text-mute mt-1 uppercase tracking-wider">{label}</div>
      </div>
    </div>
  );
}

function ProcessStep({ icon, title, desc, n }: { icon: string; title: string; desc: string; n: number }) {
  return (
    <div className="relative rounded-2xl bg-panel/50 border border-line p-5 hover:border-accent/40 transition-all duration-300 group">
      <div className="absolute top-3 right-4 text-[10px] font-mono text-mute">0{n}</div>
      <div className="text-3xl mb-3 group-hover:scale-110 transition-transform duration-300 inline-block">{icon}</div>
      <div className="text-ink text-sm font-bold mb-1">{title}</div>
      <div className="text-mute text-xs leading-relaxed">{desc}</div>
    </div>
  );
}

function SectionLabel({ children, color = "accent" }: { children: React.ReactNode; color?: "accent" | "warn" | "ok" | "cyan" }) {
  const cls = { accent: "text-accent", warn: "text-warn", ok: "text-ok", cyan: "text-cyan" }[color];
  const bg  = { accent: "bg-accent", warn: "bg-warn", ok: "bg-ok", cyan: "bg-cyan" }[color];
  return (
    <div className={`text-xs uppercase tracking-[0.2em] font-bold ${cls} mb-3 flex items-center gap-3`}>
      <span className={`w-8 h-px ${bg}`} />
      <span>{children}</span>
    </div>
  );
}

export default async function PackPage({ params }: { params: { id: string } }) {
  const stored = loadPack(params.id);
  if (!stored) notFound();

  const { pack, receipt, winnerAgent, winnerRationale, course, topic, createdAt } = stored;
  const flashcards = pack.flashcards ?? [];
  const practiceQs = pack.practiceQuestions ?? [];
  const date = new Date(createdAt).toLocaleString("en-US", {
    month: "short", day: "numeric", hour: "numeric", minute: "2-digit",
  });

  const shortTx = receipt.txHash.length > 24
    ? `${receipt.txHash.slice(0, 12)}…${receipt.txHash.slice(-8)}`
    : receipt.txHash;

  return (
    <div className="min-h-screen bg-bg text-ink font-sans antialiased">

      {/* ── Sticky glassy nav ── */}
      <nav className="sticky top-0 z-50 glass-strong border-b border-line/60">
        <div className="max-w-6xl mx-auto px-6 py-3.5 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="relative">
              <div className="w-2 h-2 rounded-full bg-accent" />
              <div className="absolute inset-0 w-2 h-2 rounded-full bg-accent animate-ping opacity-60" />
            </div>
            <span className="font-bold tracking-tight">StudyHire</span>
          </div>
          <a href="/" className="text-mute text-sm hover:text-ink transition-colors flex items-center gap-2 group">
            <span className="inline-block group-hover:-translate-x-0.5 transition-transform">←</span>
            <span>back to dashboard</span>
          </a>
        </div>
      </nav>

      {/* ── Hero ── */}
      <header className="relative hero-gradient overflow-hidden border-b border-line/60 noise">
        {/* Floating orbs */}
        <div className="absolute top-20 -left-20 w-96 h-96 rounded-full bg-accent/10 blur-3xl animate-float" />
        <div className="absolute bottom-10 -right-20 w-96 h-96 rounded-full bg-cyan/10 blur-3xl animate-float" style={{ animationDelay: "2s" }} />

        <div className="relative max-w-6xl mx-auto px-6 py-16 sm:py-24">
          <div className="animate-slide-up">
            {/* Badges */}
            <div className="flex flex-wrap items-center gap-3 mb-6">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-accent/15 border border-accent/30 text-accent text-xs font-bold tracking-wider uppercase">
                <span className="w-1.5 h-1.5 rounded-full bg-accent" />
                {course}
              </span>
              <span className="text-mute text-xs">{date}</span>
              <span className="text-line">•</span>
              <span className="text-mute text-xs">Generated by 2 competing AI agents</span>
            </div>

            {/* Big gradient title */}
            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-black tracking-tight mb-8 capitalize leading-[1.05]">
              <span className="gradient-text">{topic}</span>
            </h1>

            {/* Winner card */}
            <div className="glass rounded-2xl border border-ok/20 p-5 mb-8 max-w-2xl card-glow"
                 style={{ boxShadow: "0 8px 32px -8px rgba(51, 209, 122, 0.20)" }}>
              <div className="flex items-start gap-4">
                <div className="text-4xl animate-float">🏆</div>
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-x-2 mb-1.5">
                    <span className="text-ok font-bold text-base">{winnerAgent}</span>
                    <span className="text-mute text-sm">won the study-pack bounty</span>
                  </div>
                  {winnerRationale && (
                    <p className="text-mute text-sm italic leading-relaxed">&ldquo;{winnerRationale}&rdquo;</p>
                  )}
                </div>
              </div>
            </div>

            {/* Stats grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8 max-w-3xl">
              <Stat value={flashcards.length}                     label="Flashcards"       color="accent" />
              <Stat value={practiceQs.length}                     label="Practice Probs"   color="warn"   />
              <Stat value={`$${receipt.amountUsd.toFixed(2)}`}    label="x402 Paid"        color="ok"     />
              <Stat value="2"                                     label="Agents Competed"  color="cyan"   />
            </div>

            {/* Receipt strip */}
            <div className="flex flex-wrap items-center gap-x-3 gap-y-1.5 text-xs text-mute">
              <span className="inline-flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-ok" />
                <span>On-chain receipt</span>
              </span>
              <span className="text-line">·</span>
              <code className="font-mono text-mute">{shortTx}</code>
              {receipt.explorerUrl && receipt.txHash !== "(no_payment_required)" && (
                <>
                  <span className="text-line">·</span>
                  <a
                    href={receipt.explorerUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-accent hover:underline inline-flex items-center gap-1"
                  >
                    view on GOAT explorer
                    <span>↗</span>
                  </a>
                </>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* ── Summary ── */}
      <section className="border-b border-line/60">
        <div className="max-w-6xl mx-auto px-6 py-14">
          <div className="max-w-3xl animate-slide-up">
            <SectionLabel color="accent">Quick summary</SectionLabel>
            <p className="text-ink text-lg sm:text-xl leading-relaxed font-light">
              {pack.summary}
            </p>
          </div>
        </div>
      </section>

      {/* ── Flashcards ── */}
      <section className="border-b border-line/60 relative overflow-hidden">
        <div className="absolute top-1/2 -right-40 w-80 h-80 rounded-full bg-accent/5 blur-3xl" />

        <div className="relative max-w-6xl mx-auto px-6 py-14">
          <div className="flex flex-wrap items-end justify-between gap-4 mb-10">
            <div className="animate-slide-up">
              <SectionLabel color="accent">Flashcards</SectionLabel>
              <h2 className="text-3xl sm:text-4xl font-black tracking-tight">Test your recall</h2>
              <p className="text-mute mt-2 text-sm">{flashcards.length} cards · click any card to flip and reveal the answer</p>
            </div>
            <div className="text-xs text-mute font-mono bg-panel border border-line rounded-full px-3 py-1.5 inline-flex items-center gap-1.5 animate-slide-up">
              <span className="w-1.5 h-1.5 rounded-full bg-accent animate-pulse" />
              interactive
            </div>
          </div>

          {flashcards.length === 0 ? (
            <p className="text-mute text-sm">No flashcards generated.</p>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {flashcards.map((fc, i) => (
                <Flashcard key={i} q={fc.q} a={fc.a} n={i + 1} delay={i * 60} />
              ))}
            </div>
          )}
        </div>
      </section>

      {/* ── Practice Problems ── */}
      <section className="border-b border-line/60 relative overflow-hidden">
        <div className="absolute top-20 -left-40 w-80 h-80 rounded-full bg-warn/5 blur-3xl" />

        <div className="relative max-w-6xl mx-auto px-6 py-14">
          <div className="mb-10 animate-slide-up">
            <SectionLabel color="warn">Practice problems</SectionLabel>
            <h2 className="text-3xl sm:text-4xl font-black tracking-tight">Apply what you know</h2>
            <p className="text-mute mt-2 text-sm">{practiceQs.length} problems · hints revealed on demand</p>
          </div>

          {practiceQs.length === 0 ? (
            <p className="text-mute text-sm">No practice questions generated.</p>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 max-w-5xl">
              {practiceQs.map((pq, i) => (
                <PracticeCard key={i} q={pq.q} sketch={pq.sketch} n={i + 1} delay={i * 80} />
              ))}
            </div>
          )}
        </div>
      </section>

      {/* ── How this was made ── */}
      <section className="border-b border-line/60">
        <div className="max-w-6xl mx-auto px-6 py-14">
          <div className="mb-8 animate-slide-up">
            <SectionLabel color="cyan">Behind the scenes</SectionLabel>
            <h2 className="text-3xl sm:text-4xl font-black tracking-tight">How this pack was made</h2>
            <p className="text-mute mt-2 text-sm">A multi-agent pipeline on GOAT mainnet — every payment is on-chain</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
            <ProcessStep n={1} icon="💸" title="x402 micropayment" desc={`$${receipt.amountUsd.toFixed(2)} USDC paid to topic-extractor agent`} />
            <ProcessStep n={2} icon="⚔️"  title="2 agents competed" desc="Concise vs. narrative styles, both produced full packs" />
            <ProcessStep n={3} icon="⚖️"  title="Claude verifier judged" desc={`Picked ${winnerAgent} based on density & exam relevance`} />
            <ProcessStep n={4} icon="🔗" title="ERC-8004 identity" desc="All agents registered on GOAT mainnet (chain 2345)" />
          </div>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="py-10 text-center">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-xs text-mute mb-2">
            Generated by <span className="gradient-text font-bold">StudyHire</span>
          </div>
          <div className="text-[11px] text-mute/70">
            powered by Claude (Anthropic) · ERC-8004 agents · GOAT mainnet · OpenClaw Hackathon 2026
          </div>
        </div>
      </footer>
    </div>
  );
}
